---
title: "olsonryan.github.io"
---

## Organization Introduction

  The University of Alberta School of Business has some of the strongest program offerings in Canada, with honours paths in Finance and Certificates in Real Estate, Sustainability, and Entrepreneurship. The finance program affords students the opportunity to pursue student-directed learning courses, emulating a workplace environment. The school is equipped with enterprise-level financial tools and knowledge from renowned professors, many of whom are leaders in their respective industry.
 
  Students will have the opportunity to learn critical skills for the modern finance industry such as data science and how they intersect with conceptual topics. More than just knowledgeable, we are a group of driven individuals, constantly seeking to exceed expectations and add tangible value in the workplace. We honour the importance of continual learning and welcome mentorship opportunities to foster professional growth.

## Personal Introduction

### Ryan Olson
  I come from a bison ranching background which helped me develop a strong and unique work ethic and dedication to seeing tasks through to completion. In June 2021 I became associated with a logistics-tech startup in its earliest stages and helped develop the company into a six-figure monthly recurring revenue business. During this time I have touched nearly every aspect of the development of the startup, including sales, operations, tech, and finance. I am currently the manager of the finance department at the company. 